apiVersion: v1
kind: Service
metadata:
  name: messaging-gateway
  namespace: messaging-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5070
  selector:
    app: messaging-gateway
